float64 rpm
float64 upper_hydraulic_pressure  # Pa 
float64 lower_hydraulic_pressure  # Pa 
float64 force  # Newtons

float64 supplied_hydraulic_power  # Watts

float64 hydraulic_motor_loss
float64 relief_valve_loss
float64 motor_emf_power  # Watts

float64 motor_drive_i2r_loss
float64 motor_drive_switching_loss
float64 motor_drive_friction_loss
float64 load_dump_power
float64 battery_i2r_loss
float64 battery_storage_power
