
std_msgs/Header header  # time, seq_num

float32 rpm
float32 total_power  # watts
float32 batt_current  # amps
float32 batt_voltage  # volts
float32 hydrogen  # .14=0
float32 north_vel  # m/s
float32 east_vel  # m/s
float32 lat
float32 lon 
float32 load_cell  # lbf
float32 piston_pos  # inches
float32 upper_pres
float32 lower_pres
float32 ffd_pres  # psi
float32 target_hdg  # deg
float32 actual_hdg  # deg
float32 rudder_pos  # counts

