# IncWaveHeight Request

# x, y to evaluate height
geometry_msgs/Point[] points

# x, y is relative to buoy origin; otherwise world origin
bool use_buoy_origin

---

# IncWaveHeight Response

builtin_interfaces/Time stamp
IncWaveHeight[] heights
bool valid
