name: Build and test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # run nightly at midnight

jobs:
  tests:
    name: Build and test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - ros-distro: "jazzy"
    container:
      image: ubuntu:24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Test
        run: .github/workflows/build-and-test.sh
        env:
          ROS_DISTRO: ${{ matrix.ros-distro }}
